// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./components/atoms/Card.vue')['default']
    Dropdown: typeof import('./components/atoms/Dropdown.vue')['default']
    FooterWeb: typeof import('./components/atoms/FooterWeb.vue')['default']
    GameBoard: typeof import('./components/atoms/GameBoard.vue')['default']
    HeaderWeb: typeof import('./components/atoms/HeaderWeb.vue')['default']
    Home: typeof import('./components/organisms/Home.vue')['default']
    IconCarbonUserAvatar: typeof import('~icons/carbon/user-avatar')['default']
    PlayersForm: typeof import('./components/atoms/PlayersForm.vue')['default']
  }
}

export { }
